// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: guardianInterface

#ifndef _GUARDIANINTERFACE_UI_H
#define _GUARDIANINTERFACE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SplashScreen.h"
#include "screens/ui_Screen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_502125874);    // assets/logo (3).png
LV_IMG_DECLARE(ui_img_icn_tds_png);    // assets/icn_tds.png
LV_IMG_DECLARE(ui_img_icn_range_arrow_png);    // assets/icn_range_arrow.png
LV_IMG_DECLARE(ui_img_icn_temp_png);    // assets/icn_temp.png
LV_IMG_DECLARE(ui_img_battery_full_alt_20dp_png);    // assets/battery_full_alt_20dp.png
LV_IMG_DECLARE(ui_img_battery_horiz_075_20dp_png);    // assets/battery_horiz_075_20dp.png
LV_IMG_DECLARE(ui_img_battery_horiz_050_20dp_png);    // assets/battery_horiz_050_20dp.png
LV_IMG_DECLARE(ui_img_battery_low_20dp_png);    // assets/battery_low_20dp.png
LV_IMG_DECLARE(ui_img_battery_horiz_000_20dp_png);    // assets/battery_horiz_000_20dp.png
LV_IMG_DECLARE(
    ui_img_wifi_find_20dp_ffffff_fill0_wght400_grad0_opsz20_png);    // assets/wifi_find_20dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(ui_img_icn_wifi_on_png);    // assets/icn_wifi_on.png
LV_IMG_DECLARE(ui_img_icn_wifi_off_png);    // assets/icn_wifi_off.png
LV_IMG_DECLARE(ui_img_icn_cloud_on_png);    // assets/icn_cloud_on.png
LV_IMG_DECLARE(ui_img_icn_cloud_off_png);    // assets/icn_cloud_off.png
LV_IMG_DECLARE(ui_img_icn_food_png);    // assets/icn_food.png

// FONTS
LV_FONT_DECLARE(ui_font_Bold_Font);
LV_FONT_DECLARE(ui_font_OpenSansSemibold44);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
