// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: guardianInterface

#ifndef _UI_COMP_PANEL_H
#define _UI_COMP_PANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT panel
#define UI_COMP_PANEL_PANEL 0
#define UI_COMP_PANEL_PANELTEMPALERT 1
#define UI_COMP_PANEL_LBLTEMPVALUE 2
#define UI_COMP_PANEL_LBLTEMPLIMIT 3
#define UI_COMP_PANEL_LBLTEMPUNIT 4
#define UI_COMP_PANEL_TEMPIMAGE 5
#define _UI_COMP_PANEL_NUM 6
lv_obj_t * ui_panel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
