// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: guardianInterface

#include "../ui.h"

// COMPONENT panel

lv_obj_t * ui_panel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_panel;
    cui_panel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_panel, 156);
    lv_obj_set_height(cui_panel, 131);
    lv_obj_set_x(cui_panel, 3);
    lv_obj_set_y(cui_panel, -31);
    lv_obj_set_align(cui_panel, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(cui_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_panel, lv_color_hex(0x2B00FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_panel, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_panel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_panel, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_panel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(cui_panel, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(cui_panel, -2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_panelTempAlert;
    cui_panelTempAlert = lv_obj_create(cui_panel);
    lv_obj_set_width(cui_panelTempAlert, 156);
    lv_obj_set_height(cui_panelTempAlert, 131);
    lv_obj_set_align(cui_panelTempAlert, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_panelTempAlert, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_panelTempAlert, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_panelTempAlert, lv_color_hex(0x000426), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panelTempAlert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_panelTempAlert, lv_color_hex(0x00004E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_panelTempAlert, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_panelTempAlert, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_panelTempAlert, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_panelTempAlert, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lblTempValue;
    cui_lblTempValue = lv_label_create(cui_panel);
    lv_obj_set_width(cui_lblTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lblTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_lblTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(cui_lblTempValue, "26,5");
    lv_obj_set_style_text_color(cui_lblTempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_lblTempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_lblTempValue, &ui_font_OpenSansSemibold44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lblTempLimit;
    cui_lblTempLimit = lv_label_create(cui_panel);
    lv_obj_set_width(cui_lblTempLimit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lblTempLimit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_lblTempLimit, 5);
    lv_obj_set_y(cui_lblTempLimit, 44);
    lv_obj_set_align(cui_lblTempLimit, LV_ALIGN_CENTER);
    lv_label_set_text(cui_lblTempLimit, "Min: 16°C");
    lv_obj_set_style_text_font(cui_lblTempLimit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lblTempUnit;
    cui_lblTempUnit = lv_label_create(cui_panel);
    lv_obj_set_width(cui_lblTempUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lblTempUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_lblTempUnit, 58);
    lv_obj_set_y(cui_lblTempUnit, -13);
    lv_obj_set_align(cui_lblTempUnit, LV_ALIGN_CENTER);
    lv_label_set_text(cui_lblTempUnit, "°C");
    lv_obj_set_style_text_font(cui_lblTempUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_tempImage;
    cui_tempImage = lv_image_create(cui_panel);
    lv_image_set_src(cui_tempImage, &ui_img_icn_temp_png);
    lv_obj_set_width(cui_tempImage, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(cui_tempImage, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(cui_tempImage, -10);
    lv_obj_set_y(cui_tempImage, -10);
    lv_obj_add_flag(cui_tempImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_tempImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL_NUM);
    children[UI_COMP_PANEL_PANEL] = cui_panel;
    children[UI_COMP_PANEL_PANELTEMPALERT] = cui_panelTempAlert;
    children[UI_COMP_PANEL_LBLTEMPVALUE] = cui_lblTempValue;
    children[UI_COMP_PANEL_LBLTEMPLIMIT] = cui_lblTempLimit;
    children[UI_COMP_PANEL_LBLTEMPUNIT] = cui_lblTempUnit;
    children[UI_COMP_PANEL_TEMPIMAGE] = cui_tempImage;
    lv_obj_add_event_cb(cui_panel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_panel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_panel_create_hook(cui_panel);
    return cui_panel;
}

