// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: guardianInterface

#ifndef UI_SPLASHSCREEN_H
#define UI_SPLASHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SplashScreen
extern void ui_SplashScreen_screen_init(void);
extern void ui_SplashScreen_screen_destroy(void);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_Spinner;
extern lv_obj_t * ui_TitleLbl;
extern lv_obj_t * ui_LoadingLbl;
extern lv_obj_t * ui_Image8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

