// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: guardianInterface

#include "../ui.h"

lv_obj_t * ui_Screen = NULL;
lv_obj_t * ui_ValidArea = NULL;
lv_obj_t * ui_panelTds = NULL;
lv_obj_t * ui_panelTdsAlert = NULL;
lv_obj_t * ui_tdsImage = NULL;
lv_obj_t * ui_lblTdsValue = NULL;
lv_obj_t * ui_lblTdsUnit = NULL;
lv_obj_t * ui_tdsLimitsPanel = NULL;
lv_obj_t * ui_imgTdsDownArrow = NULL;
lv_obj_t * ui_lblTdsLimitMin = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_imgTdsUpArow = NULL;
lv_obj_t * ui_lblTdsLimitMax = NULL;
lv_obj_t * ui_panelTemp = NULL;
lv_obj_t * ui_panelTempAlert = NULL;
lv_obj_t * ui_lblTempValue = NULL;
lv_obj_t * ui_lblTempUnit = NULL;
lv_obj_t * ui_tempImage = NULL;
lv_obj_t * ui_tempLimitsPanel = NULL;
lv_obj_t * ui_imgTempDownArrow = NULL;
lv_obj_t * ui_lblTempLimitMin = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_imgTempUpArow = NULL;
lv_obj_t * ui_lblTempLimitMax = NULL;
lv_obj_t * ui_panelHeader = NULL;
lv_obj_t * ui_lblTime = NULL;
lv_obj_t * ui_panelIcons = NULL;
lv_obj_t * ui_imgWifiOn = NULL;
lv_obj_t * ui_imgWiFiOff = NULL;
lv_obj_t * ui_imgCloudOn = NULL;
lv_obj_t * ui_imgCloudOff = NULL;
lv_obj_t * ui_panelFeeder = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_Screen_screen_init(void)
{
    ui_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen, lv_color_hex(0x070037), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Screen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValidArea = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_ValidArea, 314);
    lv_obj_set_height(ui_ValidArea, 234);
    lv_obj_set_align(ui_ValidArea, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ValidArea, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ValidArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ValidArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ValidArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ValidArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ValidArea, lv_color_hex(0xFD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ValidArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ValidArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelTds = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_panelTds, 156);
    lv_obj_set_height(ui_panelTds, 131);
    lv_obj_set_x(ui_panelTds, -3);
    lv_obj_set_y(ui_panelTds, -27);
    lv_obj_set_align(ui_panelTds, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_panelTds, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelTds, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelTds, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelTds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelTds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_panelTds, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_panelTds, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panelTds, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panelTds, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_panelTds, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_panelTds, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelTds, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_panelTds, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_grad_color(ui_panelTds, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_main_stop(ui_panelTds, 10, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_grad_stop(ui_panelTds, 120, LV_PART_MAIN | LV_STATE_USER_1);

    ui_panelTdsAlert = lv_obj_create(ui_panelTds);
    lv_obj_set_width(ui_panelTdsAlert, 156);
    lv_obj_set_height(ui_panelTdsAlert, 131);
    lv_obj_set_align(ui_panelTdsAlert, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelTdsAlert, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelTdsAlert, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelTdsAlert, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelTdsAlert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panelTdsAlert, lv_color_hex(0x000039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_panelTdsAlert, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_panelTdsAlert, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panelTdsAlert, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelTdsAlert, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelTdsAlert, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_panelTdsAlert, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_tdsImage = lv_image_create(ui_panelTds);
    lv_image_set_src(ui_tdsImage, &ui_img_icn_tds_png);
    lv_obj_set_width(ui_tdsImage, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_tdsImage, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_tdsImage, -10);
    lv_obj_set_y(ui_tdsImage, -10);
    lv_obj_add_flag(ui_tdsImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tdsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTdsValue = lv_label_create(ui_panelTds);
    lv_obj_set_width(ui_lblTdsValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTdsValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTdsValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTdsValue, "430");
    lv_obj_set_style_text_font(ui_lblTdsValue, &ui_font_OpenSansSemibold44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTdsUnit = lv_label_create(ui_panelTds);
    lv_obj_set_width(ui_lblTdsUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTdsUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTdsUnit, 58);
    lv_obj_set_y(ui_lblTdsUnit, -13);
    lv_obj_set_align(ui_lblTdsUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTdsUnit, "ppm");
    lv_obj_set_style_text_font(ui_lblTdsUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tdsLimitsPanel = lv_obj_create(ui_panelTds);
    lv_obj_set_width(ui_tdsLimitsPanel, 156);
    lv_obj_set_height(ui_tdsLimitsPanel, 50);
    lv_obj_set_x(ui_tdsLimitsPanel, 0);
    lv_obj_set_y(ui_tdsLimitsPanel, 41);
    lv_obj_set_align(ui_tdsLimitsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tdsLimitsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_tdsLimitsPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tdsLimitsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tdsLimitsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tdsLimitsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tdsLimitsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_tdsLimitsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_tdsLimitsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_tdsLimitsPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tdsLimitsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tdsLimitsPanel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTdsDownArrow = lv_image_create(ui_tdsLimitsPanel);
    lv_image_set_src(ui_imgTdsDownArrow, &ui_img_icn_down_arrow_png);
    lv_obj_set_width(ui_imgTdsDownArrow, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_imgTdsDownArrow, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_imgTdsDownArrow, -57);
    lv_obj_set_y(ui_imgTdsDownArrow, 42);
    lv_obj_set_align(ui_imgTdsDownArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTdsDownArrow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTdsDownArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTdsLimitMin = lv_label_create(ui_tdsLimitsPanel);
    lv_obj_set_width(ui_lblTdsLimitMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTdsLimitMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTdsLimitMin, -36);
    lv_obj_set_y(ui_lblTdsLimitMin, 42);
    lv_obj_set_align(ui_lblTdsLimitMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTdsLimitMin, "164 ppm");

    ui_Label1 = lv_label_create(ui_tdsLimitsPanel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, " -");

    ui_imgTdsUpArow = lv_image_create(ui_tdsLimitsPanel);
    lv_image_set_src(ui_imgTdsUpArow, &ui_img_icn_up_arrow_png);
    lv_obj_set_width(ui_imgTdsUpArow, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_imgTdsUpArow, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_imgTdsUpArow, -52);
    lv_obj_set_y(ui_imgTdsUpArow, 15);
    lv_obj_set_align(ui_imgTdsUpArow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTdsUpArow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTdsUpArow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTdsLimitMax = lv_label_create(ui_tdsLimitsPanel);
    lv_obj_set_width(ui_lblTdsLimitMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTdsLimitMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTdsLimitMax, 50);
    lv_obj_set_y(ui_lblTdsLimitMax, 42);
    lv_obj_set_align(ui_lblTdsLimitMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTdsLimitMax, "254 ppm");

    ui_panelTemp = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_panelTemp, 156);
    lv_obj_set_height(ui_panelTemp, 131);
    lv_obj_set_x(ui_panelTemp, 3);
    lv_obj_set_y(ui_panelTemp, -27);
    lv_obj_set_align(ui_panelTemp, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_panelTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelTemp, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panelTemp, lv_color_hex(0x2B00FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_panelTemp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_panelTemp, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panelTemp, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_panelTemp, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_panelTemp, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panelTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panelTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_panelTemp, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_panelTemp, -2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelTempAlert = lv_obj_create(ui_panelTemp);
    lv_obj_set_width(ui_panelTempAlert, 156);
    lv_obj_set_height(ui_panelTempAlert, 131);
    lv_obj_set_align(ui_panelTempAlert, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelTempAlert, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelTempAlert, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelTempAlert, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelTempAlert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panelTempAlert, lv_color_hex(0x000039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_panelTempAlert, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_panelTempAlert, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panelTempAlert, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelTempAlert, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelTempAlert, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_panelTempAlert, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_lblTempValue = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_lblTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempValue, "26,5");
    lv_obj_set_style_text_color(ui_lblTempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTempValue, &ui_font_OpenSansSemibold44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempUnit = lv_label_create(ui_panelTemp);
    lv_obj_set_width(ui_lblTempUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTempUnit, 58);
    lv_obj_set_y(ui_lblTempUnit, -13);
    lv_obj_set_align(ui_lblTempUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempUnit, "°C");
    lv_obj_set_style_text_font(ui_lblTempUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempImage = lv_image_create(ui_panelTemp);
    lv_image_set_src(ui_tempImage, &ui_img_icn_temp_png);
    lv_obj_set_width(ui_tempImage, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_tempImage, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_tempImage, -10);
    lv_obj_set_y(ui_tempImage, -10);
    lv_obj_add_flag(ui_tempImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tempImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempLimitsPanel = lv_obj_create(ui_panelTemp);
    lv_obj_set_width(ui_tempLimitsPanel, 156);
    lv_obj_set_height(ui_tempLimitsPanel, 50);
    lv_obj_set_x(ui_tempLimitsPanel, 0);
    lv_obj_set_y(ui_tempLimitsPanel, 41);
    lv_obj_set_align(ui_tempLimitsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tempLimitsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_tempLimitsPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tempLimitsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempLimitsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempLimitsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempLimitsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_tempLimitsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_tempLimitsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_tempLimitsPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLimitsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLimitsPanel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgTempDownArrow = lv_image_create(ui_tempLimitsPanel);
    lv_image_set_src(ui_imgTempDownArrow, &ui_img_icn_down_arrow_png);
    lv_obj_set_width(ui_imgTempDownArrow, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_imgTempDownArrow, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_imgTempDownArrow, -57);
    lv_obj_set_y(ui_imgTempDownArrow, 42);
    lv_obj_set_align(ui_imgTempDownArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTempDownArrow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTempDownArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempLimitMin = lv_label_create(ui_tempLimitsPanel);
    lv_obj_set_width(ui_lblTempLimitMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempLimitMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTempLimitMin, -36);
    lv_obj_set_y(ui_lblTempLimitMin, 42);
    lv_obj_set_align(ui_lblTempLimitMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempLimitMin, "16,4 °C");

    ui_Label6 = lv_label_create(ui_tempLimitsPanel);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, " - ");

    ui_imgTempUpArow = lv_image_create(ui_tempLimitsPanel);
    lv_image_set_src(ui_imgTempUpArow, &ui_img_icn_up_arrow_png);
    lv_obj_set_width(ui_imgTempUpArow, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_imgTempUpArow, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_imgTempUpArow, -52);
    lv_obj_set_y(ui_imgTempUpArow, 15);
    lv_obj_set_align(ui_imgTempUpArow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTempUpArow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTempUpArow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTempLimitMax = lv_label_create(ui_tempLimitsPanel);
    lv_obj_set_width(ui_lblTempLimitMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempLimitMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTempLimitMax, 50);
    lv_obj_set_y(ui_lblTempLimitMax, 42);
    lv_obj_set_align(ui_lblTempLimitMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTempLimitMax, "25,4 °C");

    ui_panelHeader = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_panelHeader, 320);
    lv_obj_set_height(ui_panelHeader, 20);
    lv_obj_set_x(ui_panelHeader, 0);
    lv_obj_set_y(ui_panelHeader, 3);
    lv_obj_set_align(ui_panelHeader, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_panelHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelHeader, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_panelHeader, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_lblTime = lv_label_create(ui_panelHeader);
    lv_obj_set_width(ui_lblTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime, "12:21");
    lv_obj_set_style_text_letter_space(ui_lblTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_lblTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime, &ui_font_Bold_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelIcons = lv_obj_create(ui_panelHeader);
    lv_obj_set_width(ui_panelIcons, 332);
    lv_obj_set_height(ui_panelIcons, 20);
    lv_obj_set_align(ui_panelIcons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelIcons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelIcons, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelIcons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelIcons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelIcons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_panelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_panelIcons, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_panelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_panelIcons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWifiOn = lv_image_create(ui_panelIcons);
    lv_image_set_src(ui_imgWifiOn, &ui_img_icn_wifi_on_png);
    lv_obj_set_width(ui_imgWifiOn, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgWifiOn, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_imgWifiOn, 96);
    lv_obj_set_y(ui_imgWifiOn, -101);
    lv_obj_set_align(ui_imgWifiOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWifiOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgWifiOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgWiFiOff = lv_image_create(ui_panelIcons);
    lv_image_set_src(ui_imgWiFiOff, &ui_img_icn_wifi_off_png);
    lv_obj_set_width(ui_imgWiFiOff, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgWiFiOff, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_imgWiFiOff, -1);
    lv_obj_set_y(ui_imgWiFiOff, -2);
    lv_obj_set_align(ui_imgWiFiOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWiFiOff, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgWiFiOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgCloudOn = lv_image_create(ui_panelIcons);
    lv_image_set_src(ui_imgCloudOn, &ui_img_icn_cloud_on_png);
    lv_obj_set_width(ui_imgCloudOn, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgCloudOn, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_imgCloudOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgCloudOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgCloudOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgCloudOff = lv_image_create(ui_panelIcons);
    lv_image_set_src(ui_imgCloudOff, &ui_img_icn_cloud_off_png);
    lv_obj_set_width(ui_imgCloudOff, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgCloudOff, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_imgCloudOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgCloudOff, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgCloudOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panelFeeder = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_panelFeeder, 314);
    lv_obj_set_height(ui_panelFeeder, 74);
    lv_obj_set_x(ui_panelFeeder, 0);
    lv_obj_set_y(ui_panelFeeder, -5);
    lv_obj_set_align(ui_panelFeeder, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_panelFeeder, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_panelFeeder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelFeeder, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelFeeder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelFeeder, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelFeeder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_panelFeeder, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_panelFeeder, 150, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panelFeeder, 15, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panelFeeder, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_panelFeeder);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label5, "Next Feed: 18:20");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Bold_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen_screen_destroy(void)
{
    if(ui_Screen) lv_obj_del(ui_Screen);

    // NULL screen variables
    ui_Screen = NULL;
    ui_ValidArea = NULL;
    ui_panelTds = NULL;
    ui_panelTdsAlert = NULL;
    ui_tdsImage = NULL;
    ui_lblTdsValue = NULL;
    ui_lblTdsUnit = NULL;
    ui_tdsLimitsPanel = NULL;
    ui_imgTdsDownArrow = NULL;
    ui_lblTdsLimitMin = NULL;
    ui_Label1 = NULL;
    ui_imgTdsUpArow = NULL;
    ui_lblTdsLimitMax = NULL;
    ui_panelTemp = NULL;
    ui_panelTempAlert = NULL;
    ui_lblTempValue = NULL;
    ui_lblTempUnit = NULL;
    ui_tempImage = NULL;
    ui_tempLimitsPanel = NULL;
    ui_imgTempDownArrow = NULL;
    ui_lblTempLimitMin = NULL;
    ui_Label6 = NULL;
    ui_imgTempUpArow = NULL;
    ui_lblTempLimitMax = NULL;
    ui_panelHeader = NULL;
    ui_lblTime = NULL;
    ui_panelIcons = NULL;
    ui_imgWifiOn = NULL;
    ui_imgWiFiOff = NULL;
    ui_imgCloudOn = NULL;
    ui_imgCloudOff = NULL;
    ui_panelFeeder = NULL;
    ui_Label5 = NULL;

}
