// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: guardianInterface

#ifndef UI_SCREEN_H
#define UI_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen
extern void ui_Screen_screen_init(void);
extern void ui_Screen_screen_destroy(void);
extern lv_obj_t * ui_Screen;
extern lv_obj_t * ui_ValidArea;
extern lv_obj_t * ui_panelTds;
extern lv_obj_t * ui_panelTdsAlert;
extern lv_obj_t * ui_tdsImage;
extern lv_obj_t * ui_lblTdsValue;
extern lv_obj_t * ui_lblTdsUnit;
extern lv_obj_t * ui_tdsLimitsPanel;
extern lv_obj_t * ui_imgTdsDownArrow;
extern lv_obj_t * ui_lblTdsLimitMin;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_imgTdsUpArow;
extern lv_obj_t * ui_lblTdsLimitMax;
extern lv_obj_t * ui_panelTemp;
extern lv_obj_t * ui_panelTempAlert;
extern lv_obj_t * ui_lblTempValue;
extern lv_obj_t * ui_lblTempUnit;
extern lv_obj_t * ui_tempImage;
extern lv_obj_t * ui_tempLimitsPanel;
extern lv_obj_t * ui_imgTempDownArrow;
extern lv_obj_t * ui_lblTempLimitMin;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_imgTempUpArow;
extern lv_obj_t * ui_lblTempLimitMax;
extern lv_obj_t * ui_panelHeader;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_panelIcons;
extern lv_obj_t * ui_imgWifiOn;
extern lv_obj_t * ui_imgWiFiOff;
extern lv_obj_t * ui_imgCloudOn;
extern lv_obj_t * ui_imgCloudOff;
extern lv_obj_t * ui_panelFeeder;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

